version: '3.8'

services:
  db:
    build:
      context: ./docker/db
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 05092004
      MYSQL_DATABASE: g_prod_development
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: 05092004
    restart: always

  app:
    build:
      context: ./docker/app
    container_name: g-prod-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://rails_user:05092004@db:3306/g_prod_development
    volumes:
      - .:/var/www/app

volumes:
  db_data:
